/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/oneObst.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function OneObst(props) {
  const { nodes, materials } = useGLTF("./models/oneObst.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.004"]}
        scale={10}
      >
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials.pink}
          position={[0.02, 0.001, 0.657]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.011, 0.319, 0.011]}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.RED}
          position={[-0.029, 0.08, 0.292]}
          scale={[0.011, 0.089, 0.011]}
        />
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials.RED}
          position={[-0.218, 0.08, 0.292]}
          scale={[0.011, 0.089, 0.011]}
        />
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials.RED}
          position={[0.358, 0.08, -0.249]}
          rotation={[0, 1.571, 0]}
          scale={[0.009, 0.089, 0.009]}
        />
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials.RED}
          position={[0.358, 0.08, -0.112]}
          rotation={[0, 1.571, 0]}
          scale={[0.009, 0.089, 0.009]}
        />
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials.RED}
          position={[-0.486, 0.08, -0.249]}
          rotation={[0, 1.571, 0]}
          scale={[0.009, 0.089, 0.009]}
        />
        <mesh
          geometry={nodes.Cylinder006.geometry}
          material={materials.RED}
          position={[-0.486, 0.08, -0.112]}
          rotation={[0, 1.571, 0]}
          scale={[0.009, 0.089, 0.009]}
        />
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={materials.RED}
          position={[0.17, 0.08, 0.292]}
          scale={[0.011, 0.089, 0.011]}
        />
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials.White}
          position={[0.412, 0, 0.309]}
          scale={[0.035, 0.055, 0.035]}
        />
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials.White}
          position={[0, 0, -0.687]}
          scale={[0.331, 0.055, 0.01]}
        />
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials.White}
          position={[0, 0, 0.576]}
          scale={[0.33, 0.055, 0.01]}
        />
        <group position={[-0.029, 0.169, 0.292]} scale={[0.103, 0.035, 0.019]}>
          <mesh
            geometry={nodes.Plane006_1.geometry}
            material={materials.White}
          />
          <mesh
            geometry={nodes.Plane006_2.geometry}
            material={materials.Blue}
          />
        </group>
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials.White}
          position={[0.139, 0, -0.539]}
          scale={[0.022, 0.055, 0.022]}
        />
        <group
          position={[0.358, 0.169, -0.18]}
          rotation={[0, 1.571, 0]}
          scale={[0.044, 0.035, 0.019]}
        >
          <mesh
            geometry={nodes.Plane011_1.geometry}
            material={materials.White}
          />
          <mesh
            geometry={nodes.Plane011_2.geometry}
            material={materials.Blue}
          />
        </group>
        <group position={[-0.017, 0, -0.082]} scale={[0.025, 0.055, 0.035]}>
          <mesh geometry={nodes.Plane013.geometry} material={materials.White} />
          <mesh geometry={nodes.Plane013_1.geometry} material={materials.RED} />
        </group>
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials.White}
          position={[-0.526, 0, 0.4]}
          scale={[0.035, 0.055, 0.035]}
        />
        <group
          position={[-0.486, 0.169, -0.18]}
          rotation={[0, 1.571, 0]}
          scale={[0.044, 0.035, 0.019]}
        >
          <mesh geometry={nodes.Plane015.geometry} material={materials.White} />
          <mesh
            geometry={nodes.Plane015_1.geometry}
            material={materials.Blue}
          />
        </group>
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials.pink}
          position={[0.158, 0, 0.768]}
          scale={[0.062, 0.055, 0.035]}
        />
        <mesh
          geometry={nodes.Torus.geometry}
          material={materials.pink}
          position={[-0.296, 0.022, 0.803]}
          scale={[0.031, 0.009, 0.031]}
        />
        <mesh
          geometry={nodes.Torus003.geometry}
          material={materials.pink}
          position={[-0.296, 0.008, 0.803]}
          scale={[0.031, 0.009, 0.031]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/oneObst.glb");
