/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/sphere.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Sphere(props) {
  const { nodes, materials } = useGLTF("./models/sphere.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
      />
    </group>
  );
}

useGLTF.preload("./models/sphere.glb");
